title: 活页夹
email: yuhr123@gmail.com
description: 活页夹就是可以在上面随便写东西，喜欢的可以永远留着，不喜欢的可以随意删除。
baseurl: ''
url: '/'
twitter_username: Herald_Yu
github_username: getnas
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
show_drafts: true
paginate: 10
paginate_path: "page:num"
