---
title: 活页本
email: yuhr123@gmail.com
description: '没什么，胡言乱语而已。

'
baseurl: ''
url: ''
twitter_username: Herald_Yu
github_username: getnas
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
